### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by guyho** [corda/corda-kubernetes-deployment#1]
Thanks for preparing this, Henrik. I haven't yet had a chance to try it out, and apols for providing comments a week late, but here are early comments from just reading the doc:
- I was looking for "what problem is this solving" information. Maybe there is a predecessor document that provides all that context. Is there? If not, then this doc needs to explain what value does Kubernetes bring to a Corda Deployment, and what specific use cases are applicable (or not applicable).
- Is it the intent to explain the usage for nn number of cloud environments or is it sufficient to use Azure as a reference environment, an example, to explain how to use Kubernetes with Corda? 
- Iike what I'm seeing in the configuration options, e.g., "Enable/disable Corda Firewall use" and look forward to giving it a try.

**Comment by henrikr3** [comment]
We can discuss these issues in person, they are not related to the actual repository.
