### ISSUE TITLE
Repeated readlink errors

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#20]
When I run  ./one-time-setup.sh I get the following errors:

+ /Users/simon/corda-kubernetes-deployment/docker-images/build_docker_images.sh
+ DIR=.
+ GetPathToCurrentlyExecutingScript
++ readlink -f /Users/simon/corda-kubernetes-deployment/docker-images/build_docker_images.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]

+++ readlink -f /Users/simon/corda-kubernetes-deployment/docker-images/docker_config.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]

**Comment by henrikr3** [comment]
This has been resolved with logging improvements (there was only error outputs, not actual errors).
