### ISSUE TITLE
Add link to remove folder when starting new node.

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#25]
Add comment to remove /Users/simon/corda-kubernetes-deployment/helm/initial_registration/output/corda/templates/workspace when starting new node.

**Comment by henrikr3** [comment]
reset-environment.sh already provides this functionality:
"rm -rf $DIR/helm/initial_registration/output/corda/templates/workspace/"
Or where did you like to see this documented?

**Comment by henrikr3** [comment]
I am assuming this issue has been resolved due to lack of further comments.
