### ISSUE TITLE
Network Parameters Not Downloading for one-time-setup.sh

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#26]
@henrikr3 I'm noticing a consistent error downloading network parameters in one-time-setup.sh

This is the output:

Corda Node network-parameters step
Next we will launch the Corda Node just in order to download network-parameters file. Please wait...
Checking for network-parameters file...
Found network-parameters file!
waitTillNetworkParametersIsAvailable finished.
Copying network-parameters to helm/files/network (for Corda Firewall use).
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

*************************************************************************************************************************************
*  All rights reserved.                                                                                                             *
*  This software is proprietary to and embodies the confidential technology of R3 LLC ("R3").                                       *
*  Possession, use, duplication or dissemination of the software is authorized only pursuant to a valid written license from R3.    *
*  IF YOU DO NOT HAVE A VALID WRITTEN LICENSE WITH R3, DO NOT USE THIS SOFTWARE.                                                    *
*************************************************************************************************************************************

   ______               __         _____ _   _ _____ _____ ____  ____  ____  ___ ____  _____
  / ____/     _________/ /___ _   | ____| \ | |_   _| ____|  _ \|  _ \|  _ \|_ _/ ___|| ____|
 / /     __  / ___/ __  / __ `/   |  _| |  \| | | | |  _| | |_) | |_) | |_) || |\___ \|  _|
/ /___  /_/ / /  / /_/ / /_/ /    | |___| |\  | | | | |___|  _ <|  __/|  _ < | | ___) | |___
\____/     /_/   \__,_/\__,_/     |_____|_| \_| |_| |_____|_| \_\_|   |_| \_\___|____/|_____|

--- Corda Enterprise Edition 4.4.1 (c0ce776) ------------------------------------------------

💡  Use the "flow watch" shell command to see what flows your node is running

Logs can be found in                    : /Users/simon/corda-kubernetes-deployment/helm/initial_registration/output/corda/templates/workspace/logs
⚠️   ATTENTION: If you make use of confidential identities, there is now a more secure way of storing the associated keys, but you have to explicitly enable it with the appropriate configuration. Review the documentation to see how this can be enabled via the `freshIdentitiesConfiguration` entry. Alternatively, you can disable this warning by setting `disableFreshIdentitiesWarning` to true in the node's configuration.
I> Using policy access restrictor classpath:/jolokia-access.xml
I> Cannot join multicast group on NIF utun1: Can't assign requested address
I> Cannot join multicast group on NIF utun0: Can't assign requested address
I> Cannot join multicast group on NIF llw0: Can't assign requested address
I> Cannot join multicast group on NIF awdl0: Can't assign requested address
I> Cannot join multicast group on NIF utun1: Can't assign requested address
I> Cannot join multicast group on NIF utun0: Can't assign requested address
I> Cannot join multicast group on NIF llw0: Can't assign requested address
I> Cannot join multicast group on NIF awdl0: Can't assign requested address
network-parameters download has completed, time to ensure Corda Node process terminates as well
Killed Corda Node process.
network-parameters download has completed, time to ensure Corda Node process terminates as well
Unfortunately the network-parameters file was not downloaded/copied to the correct folder, MANUAL intervention is required.

**Comment by henrikr3** [comment]
Thanks for bringing this to my attention Simon, this has now been fixed in ( #27 ):
https://github.com/corda/corda-kubernetes-deployment/pull/27
