### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by alicer3** [corda/corda-kubernetes-deployment#31]
such error occurs during initial registration. Although the error logs says "database.initialiseSchema=true" would fix the issue, it does not. might need to consider use db migration tool.

`Database connection url is              : jdbc:sqlserver://ps-db-k8s-test.database.windows.net:1433;database=corda;user=corda@ps-db-k8s-test;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;;sendStringParametersAsUnicode=false
[ERROR] 20:33:45+0800 [main] internal.NodeStartupLogging.invoke - Exception during node registration: Incompatible database schema version detected, please run the node with configuration option database.initialiseSchema=true. Reason: There are 92 outstanding database changes that need to be run. Please use the advanced migration tool. See: https://docs.corda.r3.com/database-management.html [errorCode=1nkwe50, moreInformationAt=https://errors.corda.net/ENT/4.2/1nkwe50]
[ERROR] 20:33:45+0800 [main] internal.NodeStartupLogging.invoke - Exception during node startup: net.corda.core.utilities.Try$Failure cannot be cast to net.corda.core.utilities.Try$Success [errorCode=rmnkpl, moreInformationAt=https://errors.corda.net/ENT/4.2/rmnkpl]
`

**Comment by alicer3** [comment]
can be fixed by adding "database.runMigration = true"

**Comment by henrikr3** [comment]
This issue has been resolved by #38
