### ISSUE TITLE
Automation option for updating values.yml.

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#33]
Looking at it this deployment from the point of view of the end user say being experienced in DevOps so Docker and k8s but still learning Corda.

1. The CENM k8s deployment has values that need to go into values.yml
2. The Terraform  deployment has values that need to go into values.yml

This means if the values.yml file is edited manually, the DevOps person really needs to know Corda right now. 

I'd like to see a PPT document that comes with the deployment that explains CENM k8s, Terraform tech footprint and the variables from both that need to go in values.yml.  Also I'd like the user to have an option of automated deployment i.e. script that updates values.yml. 

In addition the PPT should have a section that shows end user how to enter the k8s shell and manually run Corda Health Survey to ping Notary.

**Comment by henrikr3** [comment]
The components you are talking about are separate components to this repository.
They may find integration points at a later date, but the current version does not have dependencies on these mentioned components and therefore will not be adding the requested documentation at this point in time.
Of course if we add the coupling to these external components, the relevant documentation should be added with them.
