### ISSUE TITLE
Output from Terraform

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#34]
@henrikr3 It would be useful to pull this information into values.yml for your deployment?

Outputs:

acr_admin_password = <sensitive information redacted>
acr_admin_username = <sensitive information redacted>
acr_host =<sensitive information redacted>
aks_host = <sensitive information redacted>
aks_password = <sensitive information redacted>
aks_username = <sensitive information redacted>
storage_account_primary_access_key = <sensitive information redacted>

**Comment by henrikr3** [comment]
Thanks for the idea Simon.
(I have updated your issue by redacting any sensitive information posted)
The Terraform scripts are currently an external repository without a strong coupling with this repository.
Should this situation change, we will of course look to automate the connection between Terraform outputs and the Corda Kubernetes Deployment!
