### ISSUE TITLE
cp: illegal option -- u still an issue in one-time-setup.sh

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#35]
Found network-parameters file!
waitTillNetworkParametersIsAvailable finished.
Copying network-parameters to helm/files/network (for Corda Firewall use).
cp: illegal option -- u
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory

**Comment by henrikr3** [comment]
This issue has been resolved by #27
