### ISSUE TITLE
Ubuntu Deployment of Scripts in Azure

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#5]
Ubuntu 18.04 x86_64 GNU/Linux

1) Made the following changes to build_docker_images.sh and push_docker_images.sh

Added the variables from docker_config.sh directly to build_docker_images.sh and push_docker_images.sh because these lines error out i.e. the variables are not sourced:

#source $DIR/docker_config.sh
#source ./docker_config.sh

Scripts completed successfully following changes.

2) On Ubuntu generate_pki.sh  I copied the proper key tool binary to the required folder and it generated this error:

/home/cordaadmin/corda-kubernetes-deployment/corda-pki-generator/pki-firewall/bin/keytool: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory

Added the following line to generate_pki.sh to get past this error. 

#KEYTOOL_EXE=$DIR/bin/keytool
KEYTOOL_EXE=/usr/bin/keytool

Scripts completed successfully following changes.

@irvnet @henrikr3

**Comment by henrikr3** [comment]
Fixed, Ubuntu 18.04 is now supported.
