### ISSUE TITLE
Ubuntu Deployment of Scripts in Aure

### ISSUE THREAD

**Issue by simonr3** [corda/corda-kubernetes-deployment#6]
Running initial registration, there is a source command in /corda-kubernetes-deployment/helm/initial_registration/output/corda/templates/initial_registration.sh that is produced by initial_registration.sh.yml references the docker_config.sh variables. This fails on execution so variables were added directly to the initial_registration.sh.yml file.

**Comment by henrikr3** [comment]
Fixed, Ubuntu 18.04 is now supported.
